---
title: "recommand"
output: html_document
---
#load data
```{r}
load.data<-function(dataname){
  if(dataname == "user"){
    data.url = "https://storage.googleapis.com/kaggle-competitions-data/kaggle/2799/kaggle_songs.txt?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1523403965&Signature=kOJWUWDXixFmhcRroGr9CNzdVci%2B7NAoCXcQEEJBFVgxqEwjY9hU6jl7iR1fMAUZQOsU%2B35XthMm4cBPU%2FGa0x7IM9ZgbqjwB1svwoRJ8nsyDnanIpRJZUvcviKajl0KIWlknnXE8M0H0DwOxgdQ8Up5MEG9icuDMb3A3OYjNpe8IqufTUfJTVDoL%2BFq0jqbQ%2BsBy%2Bkq25uP3hR3fNVeIk8BLC9mMZS7NAM7%2FoEVOKG0MTHdFOdvuR5XPcJhShDXG%2FiP1691I9ZtPbG0hcEnUpmj9Fi40Z4nLqkcNELqxvQNMJbVfDIZJEIa6Pl4IkIr6s%2FoGVvT6EvkDTOvya1mA%3D%3D"
    dataset = read.csv(data.url)
  }
  else if(dataname == "history"){
    data.url = "kaggle_visible_evaluation_triplets.txt"
    dataset = read.csv(data.url, sep = "\t",col.names = c("u_id","song_id","count"))
  }
  dataset
}
```
#analy listening history data
```{r}
history<-load.data("history")
history[1:3,]
```
ToDo：average count by user
```{r}
history[1:3,]
#user_play = tapply(history$count, history$u_id, FUN=sum)
#song_dis = tapply(history$count, history$u_id, FUN=sum)

#统计user听的次数, user ~ sum(count)
userPlay = aggregate(count ~ u_id, history, sum)
userPlay[1:3,]
#统计user的数量groupby sum(count)
#df2 <- count(df = user_play, vars = user_play$count, wt_var = user_play$u_id)
userCount = as.data.frame(table(userPlay$count))
userCount[1:3,]
#sond_distribution = aggregate(u_id ~ count, user_play, count)
#history[,list(Frequency=sum(count)),by=u_id]
```
```{r}
library(ggplot2)
ggplot(userCount, aes(x = Freq)) +
  geom_histogram(stat = "bin", binwidth = 400)
```
normalize data
```{r}
data_normalize = scale(userCount[,])
```

userFreq:
userID; the number of songs that each user listened

song_userFreq:
the number of songs that each user listened; the number of users
```{r}
history[1:3,]
userFreq = as.data.frame(table(history$u_id))
userFreq[1:3,]
summary(userFreq)
song_userFreq=as.data.frame(table(userFreq$Freq))
```
scatter plot
in order to know the distribution of songs listening frequency
```{r}
song_userFreq
plot(song_userFreq,xlab="the number of songs listened",ylab="the number of user")
ggplot(song_userFreq, aes(x = Var1,Freq)) +
  geom_bar(stat = "identity") +scale_x_discrete(breaks = seq(5,53,by = 5))+labs(title = "The distribution of the number of users on the counts of songs listened
", x = "the number of songs listened", y = "the number of user")+
theme(plot.title = element_text(hjust = 0.5))
```

```{r}
#install.packages("e1071")
library(e1071)
read.matrix.csr("mxm_dataset_test.txt")
```
```{r}
nrow(history)
songFreq = as.data.frame(table(history$count))
plot(songFreq)
songFreq
library(ggplot2)
nrow(songFreq)


#ggplot(songFreq[6:70,], aes(x = Var1,Freq)) +
#  geom_bar(stat = "identity") +scale_x_discrete(breaks = seq(5,53,by = 5))+xlab("the counts of songs listened by one user")+ylab("the #number of user")+opts(title="Plant growth\ndifferent treatment") 




ggplot(songFreq[6:70,], aes(x = Var1,Freq)) +
  geom_bar(stat = "identity") +scale_x_discrete(breaks = seq(5,53,by = 5))+labs(title = "The counts of one song listened by one user", x = "the counts of songs listened by one user", y = "the number of user")+
theme(plot.title = element_text(hjust = 0.5))
```

```{r}

summary(history$count)

```

